name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - name: Install dependencies in subfolders
        run: |
          for dir in $(find . -type d -name "node_modules" -prune -o -name "package.json" -exec dirname {} \;); do
            (cd "$dir" && npm install)
          done

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo ENV=${{ secrets.ENV }} >> .env          
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
          cat .env      
          


      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test