name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        # 여기서 하위 폴더로 이동하고 해당 폴더에 있는 package.json을 찾아서 npm install 실행
      - name: Install dependencies in subfolders
        run: |
          for dir in $(find . -type d -name "node_modules" -prune -o -name "package.json" -exec dirname {} \;); do
            (cd "$dir" && npm install)
          done

      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test